//
// Created by Ruiguo Yang on 2026/5/21.
//

#ifndef ALGORITHM_FINDTHELENGTHOFTHELONGESTCOMMONPREFIX_H
#define ALGORITHM_FINDTHELENGTHOFTHELONGESTCOMMONPREFIX_H



class FindTheLengthOfTheLongestCommonPrefix {

};



#endif //ALGORITHM_FINDTHELENGTHOFTHELONGESTCOMMONPREFIX_H
